#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           armMotor,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           clawMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           upperarmMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           rotateMotor,   tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){ // While the program is running

		//Robot movement
		if(vexRT[Btn7U] == 1){ // Moving forward

			motor[upperarmMotor] = 123;

		}
		else if(vexRT[Btn7D] == 1){ // Moving backward
			motor[upperarmMotor] = -123;
	}
		else if(vexRT[Btn7R] == 1){ // Moving left

			motor[leftMotor] = -123;
			motor[rightMotor] = -123;

		}else if(vexRT[Btn7L] == 1){ // Moving right

    	motor[rightMotor] = 123;
    	motor[leftMotor] = 123;

		}else if((vexRT[Btn7U] == 0) && (vexRT[Btn7D] == 0) && (vexRT[Btn7L] == 0) && (vexRT[Btn7R] == 0) && (vexRT[Btn5U] == 0) && (vexRT[Btn6U] == 0)){
		// Stop wheel motor movement
				motor[leftMotor] = 0; // Set left motor speed to 0
    		motor[rightMotor] = 0; // Set right motor speed to 0


		}else if(vexRT[Btn5U] == 1){ // Spinning Left

				motor[leftMotor] = -123;
	    	motor[rightMotor] = 123;

		}else if(vexRT[Btn6U] == 1){ // Spinning Right

				motor[leftMotor] = 123;
	    	motor[rightMotor] = -123;

		}

		//Arm movement
		if(vexRT[Btn8U] == 1){ // Lifting arm

			motor[armMotor] = -35; // Set arm motor speed to -35

		}else if(vexRT[Btn8D] == 1){ // Lowering arm

			motor[armMotor] = 123; // Set arm motor speed to 35

		}else if((vexRT[Btn8U] == 0) && (vexRT[Btn8D] == 0)){

			motor[armMotor] = 0; // Set arm motor speed to 0

		}

		if(vexRT[Btn8L] == 1){ // Opening claw

			motor[clawMotor] = 35;

		}else if(vexRT[Btn8R] == 1){ // Closing claw

			motor[clawMotor] = -45;

		}else if((vexRT[Btn8L] == 0) && (vexRT[Btn8R] == 0)){

			motor[clawMotor] = 0; // Set claw movement speed to 0
		}

    	if(vexRT[Btn5D] == 1){

			motor [upperarmMotor] = 123;


	}

}}
